name:                api
version:             0.1.0.0
github:              "rainbacon/api"
license:             BSD3
author:              "Aaron Reynolds"
maintainer:          "reynolds.aaron1992@gmail.com"
copyright:           "2019 Aaron Reynolds"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/rainbacon/api#readme>

dependencies:
- base >= 4.7 && < 5
- warp >= 3.0.0
- wai-routes >= 0.10.0
- text >= 1.2.0
- wai >= 3.2.0

library:
  source-dirs: src

executables:
  api-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - api

tests:
  api-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - api
